identity:
  author: "birdlex"
  name: "chkp-lakera-for-dify"
  label:
    en_US: "Check Point"
    zh_Hans: "Check Point"
    pt_BR: "Check Point"
    ja_JP: "Check Point"
  description:
    en_US: "CHKP AI Security"
    zh_Hans: "CHKP AI Security"
    pt_BR: "CHKP AI Security"
    ja_JP: "CHKP AI Security"
  icon: "logo.svg"
  icon_dark: "logo-dark.svg"

credentials_for_provider:
  lakera_guard_api_key:
    type: secret-input
    required: true
    label:
      en_US: Lakera Guard API Key
      zh_Hans: Lakera Guard API 密钥
    placeholder:
      en_US: Please input your Lakera Guard API Key
      zh_Hans: 请输入你的 Lakera Guard API 密钥
    help:
      en_US: Get your API key from the Lakera platform.
      zh_Hans: 从 Lakera 平台获取您的 API 密钥。
    url: https://platform.lakera.ai/account/api-keys

#########################################################################################
# If you want to support OAuth, you can uncomment the following code.
#########################################################################################
# oauth_schema:
#   client_schema:
#     - name: "client_id"
#       type: "secret-input"
#       required: true
#       url: https://example.com/oauth/authorize
#       placeholder:
#         en_US: "Please input your Client ID"
#         zh_Hans: "请输入你的 Client ID"
#         pt_BR: "Insira seu Client ID"
#       help:
#         en_US: "Client ID is used to authenticate requests to the example.com API."
#         zh_Hans: "Client ID 用于认证请求到 example.com API。"
#         pt_BR: "Client ID é usado para autenticar solicitações à API do example.com."
#       label:
#         zh_Hans: "Client ID"
#         en_US: "Client ID"
#     - name: "client_secret"
#       type: "secret-input"
#       required: true
#       url: https://example.com/oauth/authorize
#       placeholder:
#         en_US: "Please input your Client Secret"
#         zh_Hans: "请输入你的 Client Secret"
#         pt_BR: "Insira seu Client Secret"
#       help:
#         en_US: "Client Secret is used to authenticate requests to the example.com API."
#         zh_Hans: "Client Secret 用于认证请求到 example.com API。"
#         pt_BR: "Client Secret é usado para autenticar solicitações à API do example.com."
#       label:
#         zh_Hans: "Client Secret"
#         en_US: "Client Secret"
#   credentials_schema:
#     - name: "access_token"
#       type: "secret-input"
#       label:
#         zh_Hans: "Access Token"
#         en_US: "Access Token"

tools:
  - tools/screen_content.yaml
extra:
  python:
    source: provider/check_point_ai_security.py
